### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by Ayanami2019** [microsoft/SpareNet#4]
Thank you for sharing. What GPU are you using and how long does it take to run on ShapeNet and KITTI?

**Comment by AlphaPav** [comment]
Hello, thanks for your question!

With batch size 32, it takes 5 days for training on the ShapeNet dataset with 4 Tesla V100 GPUs. 
For inference, it takes 46 ms to generate 16,384 points on a single Nvidia V100 GPU.

We do not train the model on KITTI dataset since there is no Gound Truth in KITTI. We do inference on KITTI.
